spring:
  application:
    name: Bank
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
#  datasource:
#    url: ${users.db.url}
#    username: ${users.db.user_name}
#    password: ${users.db.password}
#  liquibase:
#    contexts: ${bank.liquibase.contexts:}
  h2:
    console:
      enabled: true
server:
  port: 9080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when-authorized
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] ${HOSTNAME}"
  file:
    name: ${bank.log.dir:target}/bank.log
  level:
    sql: debug
    web: debug
    '[org.springframework.web.servlet.DispatcherServlet]': debug
    '[org.springframework.web.client.RestTemplate]': debug
    '[com.redmath.bank]': debug

#spring.profiles.include : dev